[general]
interval = "30m"
mode = "random"
screen_layout = "multi"

[general.wallpapers]
directories = []
extensions = ["jpg", "png", "jpeg"]
recursive = true

[time_of_day]
morning = "/path/to/morning_wallpaper.jpg"
afternoon = "/path/to/afternoon_wallpaper.jpg"
evening = "/path/to/evening_wallpaper.jpg"
night = "/path/to/night_wallpaper.jpg"

[categories]
nature = ["/path/to/nature_wallpapers"]
space = ["/path/to/space_wallpapers"]
tech = ["/path/to/tech_wallpapers"]

[monthly.categories]
winter = [12, 1, 2]
spring = [3, 4, 5]
summer = [6, 7, 8]
fall = [9, 10, 11]

[monthly.wallpapers]
winter = ["/path/to/winter_wallpapers"]
spring = ["/path/to/spring_wallpapers"]
summer = ["/path/to/summer_wallpapers"]
fall = ["/path/to/fall_wallpapers"]

[display]
scaling = "fill"

[logging]
level = 3
file = ""
log_to_file = true
log_to_console = true