[general]
interval = "30m" # The interval at which the wallpaper should be changed
mode = "sequential" # The mode to change the wallpaper (random, sequential, time_of_day, category, monthly)
screen_layout = "multi" # The screen layout (multi, single)

[general.wallpapers]
directories = ["C:/Users/Timhe/Pictures/wallpapers"] # The directories to search for wallpapers
extensions = ["jpg", "png", "jpeg"] # The extensions to search for
recursive = true # Search directories recursively

[time_of_day]
morning = "/path/to/morning_wallpaper.jpg"
afternoon = "/path/to/afternoon_wallpaper.jpg"
evening = "/path/to/evening_wallpaper.jpg"
night = "/path/to/night_wallpaper.jpg"

[categories]
nature = ["/path/to/nature_wallpapers"]
space = ["/path/to/space_wallpapers"]
tech = ["/path/to/tech_wallpapers"]

# The months are represented as numbers
[monthly.categories]
winter = [12, 1, 2] 
spring = [3, 4, 5]
summer = [6, 7, 8]
fall = [9, 10, 11]

[monthly.wallpapers]
winter = ["/path/to/winter_wallpapers"]
spring = ["/path/to/spring_wallpapers"]
summer = ["/path/to/summer_wallpapers"]
fall = ["/path/to/fall_wallpapers"]

[display]
scaling = "fill"

[logging]
level = 3
file = ""
log_to_file = true
log_to_console = true